WITH O_DATE AS (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR AS C
    WHERE 
        C.CAR_TYPE IN ('SUV', '세단')
        AND NOT EXISTS (
            -- 11월에 대여 중인 차량 제외
            SELECT 1
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
            WHERE 
                H.CAR_ID = C.CAR_ID
                AND H.START_DATE <= '2022-11-30' 
                AND H.END_DATE >= '2022-11-01'
        )
)

-- 코드를 입력하세요
SELECT CAR.CAR_ID AS CAR_ID, CAR.CAR_TYPE AS CAR_TYPE, ROUND(CAR.DAILY_FEE * 30 * (1 - PLAN.DISCOUNT_RATE / 100)) AS FEE
FROM O_DATE AS CAR
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
ON CAR.CAR_TYPE = PLAN.CAR_TYPE AND PLAN.DURATION_TYPE = '30일 이상'
WHERE ROUND(CAR.DAILY_FEE * 30 * (1 - PLAN.DISCOUNT_RATE / 100)) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC