-- 코드를 입력하세요
WITH MAX_FLAVOR_J AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
    ORDER BY TOTAL_ORDER DESC
),
MAX_FLAVOR_F AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
    ORDER BY TOTAL_ORDER DESC
)

SELECT F.FLAVOR AS FLAVOR
FROM MAX_FLAVOR_F AS F, MAX_FLAVOR_J AS J
WHERE F.FLAVOR = J.FLAVOR
ORDER BY (F.TOTAL_ORDER + J.TOTAL_ORDER) DESC
LIMIT 3

