-- 코드를 입력하세요
WITH PATI AS (
    SELECT A.PT_NO, P.PT_NAME, A.APNT_NO, A.MCDP_CD, A.APNT_YMD
    FROM APPOINTMENT A
    JOIN PATIENT P
    ON A.PT_NO = P.PT_NO
    WHERE DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND A.APNT_CNCL_YN = 'N' AND A.MCDP_CD = 'CS'
), DOCT AS (
    SELECT A.APNT_NO, D.DR_NAME
    FROM DOCTOR D
    JOIN APPOINTMENT A
    ON D.DR_ID = A.MDDR_ID
)

SELECT A.APNT_NO AS APNT_NO, A.PT_NAME AS PT_NAME, A.PT_NO AS PT_NO,A.MCDP_CD AS MCDP_CD, B.DR_NAME AS DR_NAME, A.APNT_YMD AS APNT_YMD
FROM PATI A
JOIN DOCT B
ON A.APNT_NO = B.APNT_NO
ORDER BY APNT_YMD
