WITH ID_NAME AS(
    SELECT ITEM_ID, ITEM_NAME, RARITY
    FROM ITEM_INFO
),
RARITY_ID AS (
    SELECT T.ITEM_ID
    FROM ITEM_INFO I
    JOIN ITEM_TREE T ON I.ITEM_ID = T.PARENT_ITEM_ID
    WHERE I.RARITY = "RARE"
)
-- 코드를 작성해주세요
SELECT N.ITEM_ID, N.ITEM_NAME, N.RARITY
FROM ID_NAME N
JOIN RARITY_ID R ON N.ITEM_ID = R.ITEM_ID
ORDER BY N.ITEM_ID DESC
