-- 코드를 작성해주세요
WITH MAX_SIZE_COLONY AS (
    SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR
)

SELECT MS.YEAR, (MS.MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV, ED.ID
FROM MAX_SIZE_COLONY AS MS, ECOLI_DATA AS ED
WHERE YEAR(DIFFERENTIATION_DATE) = MS.YEAR
ORDER BY YEAR, YEAR_DEV