-- 코드를 입력하세요
SELECT C.CAR_ID AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN
    (
        SELECT DISTINCT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE MONTH(START_DATE) = 10
    ) AS H
ON C.CAR_ID = H.CAR_ID
WHERE CAR_TYPE = '세단'
ORDER BY CAR_ID DESC
